services:
  - type: web
    name: interface-ontologie-tsa
    env: python
    pythonVersion: 3.11.0
    buildCommand: pip install -r web/requirements.txt
    startCommand: cd web && gunicorn app:app --bind 0.0.0.0:$PORT

